<a href="https://colab.research.google.com/github/futurexskill/ai/blob/master/using_classification_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import the libraries

In [0]:
import pickle
import numpy as np

In [0]:
filename = "knnmodel.pickle"
filename2 = "sc.pickle"


## Load the Model and the Scaler

In [0]:
classifier = pickle.load(open(filename,'rb'))


In [0]:
sc = pickle.load(open(filename2,'rb'))


## Predict using the Model

In [0]:
new_pred = classifier.predict(sc.transform(np.array([[40,20000]])))
new_pred

array([0])

In [0]:
new_pred_proba = classifier.predict_proba(sc.transform(np.array([[40,20000]])))[:,1]
new_pred_proba

array([0.2])

In [0]:
new_pred = classifier.predict(sc.transform(np.array([[42,50000]])))
new_pred

array([1])

In [0]:
new_pred_proba = classifier.predict_proba(sc.transform(np.array([[42,50000]])))[:,1]
new_pred_proba

array([0.8])